hanabackend/urls.py
from django.urls import path, include, re_path
from django.http import HttpResponse
from . import views

urlpatterns = [
    # re_path(r"^index/", core_views.index, name="index"),
    re_path(
        r"^category/(?P<slug>[a-z0-9-_]+?)-(?P<category_id>[0-9]+)/$",
        views.category_index,
        name="category"),

    re_path(r"^detail/(?P<product_id>[0-9]+)/$",
        views.product_details,
        name="productdetail"),
]

hanatoneko/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
from django.http import HttpResponse
from hanabackend.urls import urlpatterns as products_urls
from hanabackend.views import Index

urlpatterns = [
    #    path('admin/', admin.site.urls),
    re_path( r'^robots.txt$', lambda r: HttpResponse( "User-agent: *\nDisallow: /",
                                                      content_type="text/plain"
                                                      )
    ),
    re_path( r"^$", Index, name="index" ),
    re_path( r"^products/", include((products_urls,"product"), namespace="products")),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>

templates/category_product_list.html
{% extends "base.html" %}

{% block content %}


{% for categ in categories %}
    <a href="{% url 'products:category' categ.slug categ.id %}">{{ categ.name }}</a>
    <br>
{% endfor %}


{% for product in products_paginated %}
    <a href="{% url 'products:productdetail' product.id %}">{{ product.name }}</a>
    <br>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ products_paginated.number }} of {{ products_paginated.paginator.num_pages }}.
        </span>
        {% if has_next %}
            <a href="?page={{ next_page_number }}">next</a>
            <a href="?page={{ products_paginated.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for categ in categories_list %}
        <a href="{% url 'products:category' categ.slug categ.id %}">{{ categ.name }}</a>
    {% endfor %}

    <h2>Products</h2>
    <ul>
        {% for product in products_list %}
            <li>{{ product.name }}</li>
        {% endfor %}
    </ul>

{% endblock %}

templates/product_details.html
{% extends "base.html" %}

{% block content %}




{% endblock %}